### ISSUE TITLE
Turbo package for encryption and decryption of the data.

### ISSUE THREAD

**Issue by SkidGod4444** [SkidGod4444/plura#62]
To securely store encrypted data in our database, you can use AES-256 (Advanced Encryption Standard) for symmetric encryption.
And to do this, create a turbo package that is simple to use on both the frontend and backend.

**Comment by sadam-m** [comment]
You can do encryption before storing the data into the database.What's the use of having a turbopackage?.

**Comment by SkidGod4444** [comment]
assigning to @sadam-m
