### ISSUE TITLE
Realtime notification service.

### ISSUE THREAD

**Issue by SkidGod4444** [SkidGod4444/plura#63]
We need the live notification to be retrieved from a single api on the notification db update, so you can create a live notification service with socket.io or any other framework you like. In frontend, we just want to listen to a single end point, which will update the notification tab automatically.

**Comment by sadam-m** [comment]
bascially do you need an API for sending notification?.

**Comment by ayushhunt** [comment]
Assign me

**Comment by Rock007k** [comment]
Assign me
