### ISSUE TITLE
Test cases for all the /user api endpoints and add /user/update route

### ISSUE THREAD

**Issue by SkidGod4444** [SkidGod4444/plura#80]
For the `/user` route, create test cases for each endpoint we have.
And make a `/user/update` route that will update the users details like `name` and `image` for now. 
And it should detect the logged-in user by it's ID. You can access the logged-in user by making a request to `/user/self` If the user is not logged in, then it should update the details of the ID of the user provided in the `JSON` payload.

**Comment by sadam-m** [comment]
assign me
