### ISSUE TITLE
Add mails section

### ISSUE THREAD

**Issue by SkidGod4444** [SkidGod4444/plura#87]
Include the mail section in `app.plura.pro` so that the marketing lead is displayed. Make sure to add some integrations for exporting them, most likely **convertkit, resend & loops**

**Comment by rxhul18** [comment]
Hello, I would to on this also.
Just give me some context where to have that mail section on website or if there is design then provide me

assign-me

**Comment by SkidGod4444** [comment]
> Hello, I would to work on this also. Just give me some context where to have that mail section on website or if there is design then provide me
> 
> assign-me

To assign any issues you need to have a meet with us! Let's have a meet on 5th Dec pick any time slot cal.com/saidevdhal

**Comment by SkidGod4444** [comment]
@rxhul18 feel free to join the discord community https://discord.gg/P2NZAC7N
