### ISSUE TITLE
Create workspace api endpoints

### ISSUE THREAD

**Issue by SkidGod4444** [SkidGod4444/plura#97]
![plura_db_schema](https://github.com/user-attachments/assets/a93915f5-6d09-4487-bde8-77ffa88ccd08)

Make an API endpoint with all these details in the workspace schema with `CRUD` operations.
And cursor pagination on `GET` all endpoint.

**Comment by suryanshsoni120** [comment]
I will work on it

**Comment by SkidGod4444** [comment]
> I will work on it

Assigned!

**Comment by wtfdivyansh** [comment]
assign me
